# Generated by Django 3.2.23 on 2024-01-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
