# Generated by Django 3.2.23 on 2024-01-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firsr_name',
            new_name='first_name',
        ),
    ]
