# Generated by Django 3.2.23 on 2024-01-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240122_1325'),
        ('accounts', '0004_rename_firsr_name_user_first_name'),
    ]

    operations = [
    ]
